In [2]:
#selection techniques
import numpy as np
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [4]:
np.exp(sample_array) #exponentional

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [6]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [7]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
np.max(sample_array)

19

In [9]:
np.min(sample_array)

1

In [12]:
np.argmax(sample_array)

18

In [13]:
np.argmin(sample_array)

0

In [14]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [15]:
np.mul(sample_array)

AttributeError: module 'numpy' has no attribute 'mul'

In [16]:
np.std(sample_array)

5.477225575051661

In [17]:
np.var(sample_array)

30.0

In [18]:
np.mean(sample_array)

10.0

In [19]:
np.mode(sample_array)

AttributeError: module 'numpy' has no attribute 'mode'

In [20]:
array=np.random.randn(3,4)
array

array([[ 0.14667517,  0.21513844,  0.56371688,  0.50670102],
       [ 0.54218254,  0.21849279, -1.26324955, -0.43246609],
       [-1.26393276, -0.74635046, -0.15643132, -0.68454045]])

In [22]:
np.round(array,decimals=2)

array([[ 0.15,  0.22,  0.56,  0.51],
       [ 0.54,  0.22, -1.26, -0.43],
       [-1.26, -0.75, -0.16, -0.68]])

In [24]:
sports=np.array(['nis','maloth','circket','nis'])
np.unique(sports)

array(['circket', 'maloth', 'nis'], dtype='<U7')

In [ ]:
#PANDAS
#to create the data set   

In [33]:
import pandas as pd
import numpy as np
#pandas data framing and indexing
sport1=pd.Series([1,2,3,4],index=['circet','basket ball','carrom','vally ball'])
sport1

circet         1
basket ball    2
carrom         3
vally ball     4
dtype: int64

In [34]:
sport1=pd.Series([1,2,3,4],index=['circet','basket ball','carrom','vally ball'])
sport1

circet         1
basket ball    2
carrom         3
vally ball     4
dtype: int64

In [35]:
sport2=pd.Series([14,26,18,19],index=['kabbadi','hockey','baseball','golf'])
sport2

kabbadi     14
hockey      26
baseball    18
golf        19
dtype: int64

In [36]:
sport1+sport2

baseball      NaN
basket ball   NaN
carrom        NaN
circet        NaN
golf          NaN
hockey        NaN
kabbadi       NaN
vally ball    NaN
dtype: float64

In [39]:
import pandas as pd
import numpy as np
df1=pd.DataFrame(np.random.rand(8,5),index='a b c d e f g h'.split(),columns='socre1 socre2 socre3 socre4 socre5'.split())
df1

socre1    socre2    socre3    socre4    socre5
a  0.730123  0.265928  0.408315  0.281013  0.781496
b  0.196603  0.595535  0.464015  0.741438  0.719645
c  0.260163  0.629183  0.213716  0.640214  0.994300
d  0.787561  0.398819  0.269820  0.814665  0.654359
e  0.965536  0.397912  0.278849  0.792150  0.674849
f  0.524322  0.753109  0.797886  0.997359  0.952674
g  0.415300  0.055522  0.917342  0.906491  0.339014
h  0.559580  0.691271  0.589210  0.146111  0.647544

In [42]:

df1["socre1"]

a    0.730123
b    0.196603
c    0.260163
d    0.787561
e    0.965536
f    0.524322
g    0.415300
h    0.559580
Name: socre1, dtype: float64

In [45]:
df1[["socre1","socre2","socre3"]]

socre1    socre2    socre3
a  0.730123  0.265928  0.408315
b  0.196603  0.595535  0.464015
c  0.260163  0.629183  0.213716
d  0.787561  0.398819  0.269820
e  0.965536  0.397912  0.278849
f  0.524322  0.753109  0.797886
g  0.415300  0.055522  0.917342
h  0.559580  0.691271  0.589210

In [48]:
df1["socre6"]=df1["score1"]+df1["score2"]
df1["socre6"]

KeyError: 'score1'

In [50]:
df1['score6']=df1['score1']+df1['score2']
df1

KeyError: 'score1'

In [58]:
df2={'ID':['101','102','103','104','105'],'Name':['Nishanth','Jeeny','Niharika','Veeranna','Jamuna'],'Profit':[20,56,57,38,109]}
df=pd.DataFrame(df2)
df

ID      Name  Profit
0  101  Nishanth      20
1  102     Jeeny      56
2  103  Niharika      57
3  104  Veeranna      38
4  105    Jamuna     109

In [57]:
df2={'ID':['101','102','103','104','105'],'Name':['nis','maloth','rock','star','boy'],'profit':[12,34,56,7,8]}
df=pd.DataFrame(df2)
df

ID    Name  profit
0  101     nis      12
1  102  maloth      34
2  103    rock      56
3  104    star       7
4  105     boy       8

In [59]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [62]:
df[["ID","Name","profit"]]


KeyError: "['profit'] not in index"

In [63]:
df[["ID","Name","profit"]]

KeyError: "['profit'] not in index"

In [ ]:
df=df.drop("ID",axis=1)

In [66]:
df

Name  Profit
0  Nishanth      20
1     Jeeny      56
2  Niharika      57
3  Veeranna      38
4    Jamuna     109

In [67]:
df.drop(3)

Name  Profit
0  Nishanth      20
1     Jeeny      56
2  Niharika      57
4    Jamuna     109