In [ ]:
#numpy: package for multidimensional array


In [ ]:
import numpy as np

In [3]:
import numpy as np
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [4]:
aar =np.array([2,3,4])
aar

array([2, 3, 4])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[4,9,8]]
list_of_lists
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 9, 8]])

In [8]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [9]:
np.arrange(1,100)

AttributeError: module 'numpy' has no attribute 'arrange'

In [10]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,31,5)#shift+tab->help box

array([ 1,  6, 11, 16, 21, 26])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones(2,3,9)

TypeError: Cannot interpret '3' as a data type

In [19]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.zeros((2,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
 np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [24]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,5)

array([[0.61081585, 0.37139751, 0.60948748, 0.22687496, 0.12569961],
       [0.27721509, 0.49551545, 0.65390594, 0.59833249, 0.22948686],
       [0.02282763, 0.52472528, 0.09675297, 0.85603905, 0.54747787]])

In [26]:
np.random.randn(2,4)

array([[-2.34676909,  0.45346972, -1.43347022, -1.47277202],
       [ 0.20135006, -0.41076478,  1.5597166 ,  0.35280252]])

In [27]:
arr = np.random.randn(2,3)
arr

array([[-1.39127605, -0.99833551, -1.27227844],
       [ 0.46163054,  0.66946787, -0.57234105]])

In [29]:
np.random.randint(2,100)

43

In [31]:
np.random.randint(20,56,100)

array([43, 48, 44, 47, 38, 47, 43, 47, 44, 38, 54, 47, 44, 36, 51, 20, 33,
       55, 45, 34, 28, 30, 35, 41, 43, 42, 33, 32, 21, 22, 22, 34, 44, 54,
       20, 53, 40, 37, 20, 41, 27, 35, 32, 47, 45, 29, 26, 49, 39, 26, 53,
       44, 39, 38, 43, 39, 32, 51, 31, 26, 27, 30, 32, 23, 53, 47, 37, 55,
       45, 32, 47, 41, 40, 38, 28, 53, 46, 32, 55, 52, 26, 47, 38, 48, 53,
       27, 26, 32, 51, 51, 50, 41, 43, 55, 33, 46, 30, 52, 43, 40])

In [33]:
lists= np.arange(4,5)
lists


array([4])

In [35]:
samle_array =np.random.randint(1,24,56)
samle_array

array([21, 13, 23,  2,  8,  1,  2,  9,  2, 15,  4, 19,  5, 14,  1, 20, 19,
        5, 12,  3, 23, 20, 11, 20,  4,  1, 15, 22,  4, 21,  2,  6,  9,  1,
        7,  4, 23, 11, 20, 14, 21,  5, 19,  6, 14, 18,  9, 20, 19, 13,  7,
        7,  4,  6,  5,  9])

In [62]:
sample_array=np.array([2,3])
sample_array.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [64]:
sample_array.reshape(4,3)


ValueError: cannot reshape array of size 2 into shape (4,3)

In [60]:
rand_array=np.array([91,2,4,5])
rand_array.max()

91

In [61]:
rand_array.argmax()

0

In [46]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
a=np.random.rand(2,3)
a

array([[0.87738368, 0.29250762, 0.74158485],
       [0.80693712, 0.72146696, 0.28315018]])

In [49]:
a.T

array([[0.87738368, 0.80693712],
       [0.29250762, 0.72146696],
       [0.74158485, 0.28315018]])

In [50]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
sample_array[0]

10

In [52]:
sample_array[2:5]

array([12, 13, 14])

In [55]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [56]:
sample_array[1:3]='nis'
sample_array

ValueError: invalid literal for int() with base 10: 'nis'

In [57]:
subset_sample_array =sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [59]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [ ]:
#TWO DIMENSIONAL ARRAY

In [66]:
import numpy as np
sample_matrix =np.array([[12,23,56],[1,565,89],[34,569,78]])
sample_matrix
                                                

array([[ 12,  23,  56],
       [  1, 565,  89],
       [ 34, 569,  78]])

In [67]:
sample_matrix[1,2]

89

In [68]:
sample_matrix[2,:]

array([ 34, 569,  78])

In [69]:
sample_matrix[2]

array([ 34, 569,  78])

In [72]:
sample_matrix[:,(3,2)]

IndexError: index 3 is out of bounds for axis 1 with size 3